name: Build

on:
  pull_request:
    branches: [ stage ]

jobs:
  release-project:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: sawib-win64
          path: ./
      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          release_name: Release ${{ steps.bump_version.outputs.new_tag }}
          draft: false
          prerelease: false
      - name: Upload the release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sawib-win64.zip
          asset_name: sawib-win64.zip
          asset_content_type: application/zip

  build-project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Removing Proxy - 1
        run: npm config rm proxy
      - name: Removing Proxy - 2
        run: npm config rm https-proxy
      - name: Install dependencies
        run: yarn install --network-timeout 1000000
      - name: Build main process
        run: yarn build:main
      - name: Build renderer process
        run: yarn build:renderer
      - name: Test
        run: yarn test
      - name: Build
        run: yarn make
      - name: Zip Project
        uses: vimtor/action-zip@v1
        with:
          files: release/build/win-unpacked
          dest: ./sawib-win64.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sawib-win64
          path: ./sawib-win64.zip
